server:
  port: 8080

logging:
  level:
    org.springframework.security: ERROR
    org.springframework.web: ERROR

spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        issuer: "http://localhost:8080"
        client:
          web-client:
            registration:
              client-name: "Web Client"
              client-id: "web-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/web-client-oidc"
                - "http://127.0.0.1:8080/authorized"
              scopes:
                - "openid"
                - "trade"
            require-authorization-consent: true